### ISSUE TITLE
codecov has been discontinued

### ISSUE THREAD

**Issue by juanedu** [ibm-developer-skills-network/wtecc-CICD_PracticeCode#24]
Github actions fails on installing dependencias because codecov has been discontinued as informed on https://github.com/codecov/codecov-python

Error message on action run:
ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: none)
ERROR: No matching distribution found for codecov==2.1.12
Error: Process completed with exit code 1.

Solution:
commenting/removing codecov from requirements.txt worked for me.

**Comment by rofrano** [comment]
Thanks for letting us know @juanedu . This has been an absolute nightmare. I've spent the last day cleaning up their mess. :(
