### ISSUE TITLE
error: unable to recognize "tasks.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1" in Week3Lab1

### ISSUE THREAD

**Issue by photonicVision** [ibm-developer-skills-network/wtecc-CICD_PracticeCode#8]
Lab Week 3 Lab1 not able to complete I'm not sure if the following labs have the same error.

steps to recreate:
```
% git clone https://github.com/ibm-developer-skills-network/wtecc-CICD_PracticeCode.git
% cd wtecc-CICD_PracticeCode/labs/01_base_pipeline/
#Edit tasks.yaml appropriately
% kubectl apply -f tasks.yml
```

![tasksyamlerror](https://user-images.githubusercontent.com/111817804/188325243-956157ac-7b76-4670-89f8-0883636ef016.png)

**Comment by rofrano** [comment]
@photonicVision How did you start the lab? From Coursera? From Author Workbench? This lab requires a **Cloud IDE with OpenShift** environment and that error suggests that you were not in that environment because the `kind: Task` was not defined which is a Tekton CRD that comes with the OpenShift environment.

If this error happened from Coursera, it could be that the lab is not linked to the proper environment.

**Comment by martourez21** [comment]
I faced a similar issue but later solved it by installing tekton before starting the tekton labs on a cluster i created on ibmcloud.
use this command to install tekton.:  kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

**Comment by rofrano** [comment]
@martourez21 The issue was identified and fixed. It turns out tat the labs were launching with the wrong environment. We just fixed this yesterday so it should work fine from this point forward. Just restart the lab and you should get the correct environment.

**Comment by martourez21** [comment]
ok thank you

**Comment by photonicVision** [comment]
@rofrano I was in the lab environment when those errors were being thrown.  I'm glad the issue was able to be identified and fixed!-I just ran through the lab again and everything worked great looking forward to completing the remaining Tekton labs!  I saw other individuals posting problems with the same issue in the Coursera forums but usually it just takes to long to get resolved there if ever (take a ticket). So i posted here, in true DevOps fashion.  Thanks for fixing in timely manner! Enjoying the course and the labs thank you for your teaching effort! 

#Adding "Collaborated with IBM DevOps Champion John Rofrano previously" on my Resume

Side Note (Positive Feedback): Previously in many of the other IBM course labs there has been several issues with the labs being outdated or other code issues in labs not being fixed.  The way you have implemented the course labs (all together here in a single repo) works very well for the students to help maintain the common errors which could be of great value for students to help learning to contribute to open source projects in some way while also keeping lab code as up to date as possible. I'm not sure if the message is properly relayed through the Coursera forums to get the the labs edited with the current correct code implementations for version compatibility, repository source code errors, and what not.

**Comment by rofrano** [comment]
@photonicVision Thanks or the kind words. I'm glad you alerted me to the error in true DevOps fashion. This is how we should be collaborating all the time. At the end of the day... we're all just software engineers trying to learn form each other. I'll pass along your feedback to the team.
